version: 2
updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: miniflare
      - dependency-name: workerd
      - dependency-name: '@cloudflare/vite-plugin'
      - dependency-name: '@cloudflare/workers-types'
      - dependency-name: '@astrojs/cloudflare'
      - dependency-name: wrangler
    groups:
      cloudflare-runtime:
        patterns:
          - miniflare
          - workerd
          - '@cloudflare/*'
          - '@astrojs/cloudflare'
          - wrangler
    open-pull-requests-limit: 1
    commit-message:
      prefix: build
