$schema: ../cache/schemas/tasks.json

implicitInputs:
  - /bun.lock
  - /package.json
  - /tsconfig.options.json
  - /.prototools
  - /biome.json
  - "{package,tsconfig}.json"

tasks:
  lint:
    command: biome check --no-errors-on-unmatched .
    inputs: ["**/*"]

  fix:
    command: biome check --write --no-errors-on-unmatched .
    options:
      cache: false

  typecheck:
    command: tsc --build
    options:
      cache: false
